py3: partially fix pager spawning on Windows
Previously, spinning up the pager crashed because the command and environment
was in bytes.  (See also 543a788eea2d.)  Now it aborts with an invalid handle:

    $ HGMODULEPOLICY=py py -3 ../hg --traceback --config extensions.evolve=!
    Traceback (most recent call last):
    File "c:\Users\Matt\projects\hg\mercurial\ui.py", line 967, in _write
      self.fout.write(''.join(msgs))
    File "c:\Users\Matt\projects\hg\mercurial\windows.py", line 173, in write
      self.fp.write(s[start:end])
    OSError: [WinError 6] The handle is invalid

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\Users\Matt\projects\hg\mercurial\scmutil.py", line 164, in callcatch
        return func()
      File "c:\Users\Matt\projects\hg\mercurial\dispatch.py", line 350, in _runcatchfunc
        return _dispatch(req)
      File "c:\Users\Matt\projects\hg\mercurial\dispatch.py", line 930, in _dispatch
        return commands.help_(ui, 'shortlist')
      File "c:\Users\Matt\projects\hg\mercurial\commands.py", line 2930, in help_
        ui.write(formatted)
      File "c:\Users\Matt\projects\hg\mercurial\ui.py", line 948, in write
        self._writenobuf(*args, **opts)
      File "c:\Users\Matt\projects\hg\mercurial\ui.py", line 960, in _writenobuf
        self._write(*msgs, **opts)
      File "c:\Users\Matt\projects\hg\mercurial\ui.py", line 969, in _write
        raise error.StdioError(err)
    mercurial.error.StdioError: [Errno 9] The handle is invalid
    abort: The handle is invalid

The interesting bit here is that the abort message is marked with ANSI color,
but the OSError is not.