cext: stop preprocessing a partial function call
MSVC++ 14 yelled:

    mercurial/cext/revlog.c(1913): fatal error C1057: unexpected end of file in
                                   macro expansion

At this point, the C extensions build (with warnings), and it dies in win32.py
because the `_fields_` strings in the ctypes classes are being converted to
bytes by the source translator.