chgserver: use relative path at socket.bind
Before this patch, if the server address is long, the server will fail to
listen and throw the error:

  socket.error: AF_UNIX path too long

It is because AF_UNIX path usually has a very short length limit (107 chars on
common platforms, see sys/un.h).

This patch addresses the issue by using relative path instead. Therefore the
directory length does not matter. It helps run tests with chg using a long
$TMPDIR.