packaging: add pygit2 to the py3 Windows installers
This is needed to be able to use the git extension.

The extension no longer complains about the library being not installed, but
`hg log -r .` on a repo that works in WSL yielded a TypeError:

      ...
      File "mercurial.hg", line 188, in _peerorrepo
      File "mercurial.localrepo", line 3224, in instance
      File "mercurial.localrepo", line 623, in makelocalrepository
      File "hgext.git", line 117, in _makestore
      File "hgext.git", line 48, in __init__
    TypeError: Repository unable to unpack backend.

Differential Revision: https://phab.mercurial-scm.org/D9405